Suggestion: Add initial support for Lerna monorepos
jasonnutter/vscode-search-node-modules pull request #11
Opened 2019-05-06 12:24 UTC by orimwix

This is a suggestion to support searching the `node_modules` of child packages in `lerna` monorepos.

(related to #10)

### background ###
Workspaces that use `lerna` usually have the following file structure:
```
/node_modules
/package.json
/lerna.json

/packages/project-a 
  /node_modules
  /package.json

/packages/project-b/
  /node_modules
  /package.json
```

Currently, for workspaces with this structure, the extension will search only in the root `/node_modules`, leaving the user unable to search in one of the child projects.

With this PR, the user will be prompted to select which project to search in. 
![image](https://user-images.githubusercontent.com/32811901/57223420-a4e78480-700e-11e9-8fe2-d9d82d3f7c60.png)

### Logic ###
The logic that is used is as follows:

1. If there is no `lerna.json` file at the root level - continue as before
2. read `lerna.json` file, and look at the `packages` field. 
Example json config file:
```
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
3. Search for packages matching the pattern(s) using `glob`.
a package is a folder containing a `pakage.json` file

4. If no packages are found - search the root `/node_modules` as before

5. Prompt the user to choose a project to search in: either the root or one of the packages

6. Search the selected project's `/node_modules` folder using the existing logic

Please tell me what you think. 
If you agree with this direction, I would gladly extend the support to also include `yarn` or other types of projects.

2019-05-07 04:55 UTC, jasonnutter commented
This looks great, thanks for the contribution! I tried a couple times to get this working and kept getting stuck, nice to see someone get it figured out.

I have some small pieces of feedback, would you like that now, or were you thinking of adding the yarn support to this PR (if you think yarn support may drastically change this PR, I'll wait to provide any detailed feedback until that's ready)?

Thanks!

2019-05-07 07:40 UTC, orimwix commented
Please provide any feedback! I will address it as soon as possible :)

2019-05-07 12:56 UTC, orimwix commented
I just added a commit with support for `Yarn` workspaces.

It works exactly the same, apart from looking in `package.json/workspaces` instead of `lerna.json/packages`

2019-05-07 15:30 UTC, jasonnutter commented
Awesome, I'll take a closer look today! 

One question: one thing I kept getting hung up on was how to properly implement support for when VS Code / yarn / lerna workspaces are nested, e.g. a lerna workspace inside a VS Code workspace. Would that be supported with this implementation?

2019-05-07 15:36 UTC, jasonnutter commented
Ultimately not a blocker if not, as that is something that could be added incrementally. Just wanted to see if that was considered.

2019-05-07 15:49 UTC, orimwix commented
I actually kept it in mind, and this case is fully supported.

Let's say your workspace looks like this:
```
/regular-repo
    /node_modules
    /package.json

/lerna-repo
    /node_modules
    /lerna.json
    /packages/project1
        /package.json
        /node_modules

    /packages/project2
        /package.json
        /node_modules

```
you will first be prompted to choose between `regular-repo` and `lerna-repo`. If you chose `lerna-repo`, only then you will be prompted to choose between `project1` and `project2`

2019-05-07 16:47 UTC, jasonnutter requested changes
Left a couple comments, otherwise this looks great, thanks again for the contribution!

2019-05-07 16:47 UTC, jasonnutter commented on find-child-packages.js
> +    const config = await loadJsonFile(path.join(root, LERNA_CONFIG_FILE));
If this fails for some reason, e.g. malformed json, maybe we could show an error message?

2019-05-07 16:47 UTC, jasonnutter commented on find-child-packages.js
> +    const config = await loadJsonFile(path.join(root, PACKAGE_JSON_FILE));
Same here about catching errors and showing an error message.

2019-05-07 16:47 UTC, jasonnutter commented on find-child-packages.js
> +    if (pattern.includes('**')) return [];
I like the consts above for lerna/package.json, could we make this a const as well, to make it clear what this string is?

2019-05-07 16:47 UTC, jasonnutter commented on find-child-packages.js
> +    if (!(await exists(path.join(root, PACKAGE_JSON_FILE)))) {
Small nitpick: I personally like seperating these into two statements, makes it a little easier to read.

```js
const packageJsonExists = await exists(path.join(root, PACKAGE_JSON_FILE));
if (!packageJsonExists) {
  // ... 
}
```

2019-05-08 09:00 UTC, orimwix commented
Thanks for your quick review and feedback!
I committed the requested changes

2019-05-18 18:16 UTC, jasonnutter approved these changes

2019-05-18 18:17 UTC, jasonnutter commented
Apologies for the delay, have been on vacation and forgot to circle back on this. I'll get this merged and published this weekend. Thanks again!

2019-05-18 18:19 UTC, merged

2019-05-30 12:56 UTC, OriMarron commented
@jasonnutter Hi, any news on publishing a new version?

2019-06-03 06:05 UTC, jasonnutter commented
Sorry for the delay, working on it! See my comment on #13

2023-08-13 07:33 UTC, OrenZak commented
@jasonnutter when will be a release ?